project:
  type: website
  output-dir: "docs"

lang: es

website:
  title: "Mi Sitio Web"
  navbar:
    left:
      - href: index_main.qmd
        text: Inicio
      - href: about.qmd
        text: Sobre mí
      - text: Cursos
        menu:
          - text: "CA0721: Probabilidad"
            href: cursos/CA0721/index_CA0721.qmd
          - text: "CA0306: Contingencias de Vida I"
            href: cursos/CA0306/index_CA0306.qmd

  page-footer:
    center: |
      © 2025 | [LinkedIn](https://linkedin.com/in/tuusuario) | [Correo](diegovv13@gmail.com)

format:
  html:
    theme: flatly
    css: styles.css
    toc: true