project:
  type: website
  output-dir: "docs"

lang: es

website:
  title: "Diego Alberto Vega Víquez"
  navbar:
    left:
      - href: index_main.qmd
        text: Inicio
      - href: about.qmd
        text: Sobre mí
      - text: Cursos
        menu:
          - text: "CA0721: Probabilidad"
            href: cursos/CA0721/index_CA0721.qmd
          - text: "CA0306: Contingencias de Vida I"
            href: cursos/CA0306/index_CA0306.qmd

  sidebar:
    - id: ca0721
      title: "CA0721: Probabilidad"
      contents:
        - href: cursos/CA0721/index_CA0721.qmd
          text: "Página principal del curso"
        - href: cursos/CA0721/antecedentes_CA0721.qmd
          text: "Tema 1: Preliminares"
        - href: cursos/CA0721/intro_proba_CA0721.qmd
          text: "Tema 2: Introducción a la Probabilidad"
        - href: cursos/CA0721/teoria_general_proba_CA0721.qmd
          text: "Tema 3: Teoría General de la Probabilidad"
        - href: cursos/CA0721/variables_aleatorias_CA0721.qmd
          text: "Tema 4: Variables Aleatorias"
    - id: ca0306
      title: "CA0306: Contingencias de Vida I"
      contents:
        - href: cursos/CA0721/index_CA0306.qmd
          text: "Página principal del curso"
        - href: cursos/CA0721/distribuciones_sobrevivencia_CA0306.qmd
          text: "Tema 1: Distribuciones de Sobrevivencia"
      


  page-footer:
    center: |
      © 2025 | [LinkedIn](https://www.linkedin.com/public-profile/settings?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_self_edit_contact-info%3B4s9KlG5%2FTXOzWHwBdfCQpA%3D%3D) | [Correo](diegovv13@gmail.com)

format:
  html:
    theme: flatly
    css: styles.css
    toc: true