project:
  type: website

website:
  title: "CA0306: Contingencias de Vida I"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index_CA0306.qmd
      - distribuciones_sobrevivencia_CA0306.qmd

format:
  html:
    theme: flatly
    toc: true