project:
  type: website
  
lang: es

website:
  title: "CA0721: Probabilidad"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index_CA0721.qmd
      - antecedentes_CA0721.qmd
      - intro_proba_CA0721.qmd
      - teoria_general_proba_CA0721.qmd
      - variables_aleatorias_CA0721.qmd

format:
  html:
    theme: flatly
    toc: true